version: '3'
services:
  app:
    depends_on:
      mysql_server:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_DATABASE=mysql_server
      - MYSQL_PASSWORD=123456root
      - MYSQL_ROOT_PASSWORD=123456root
      - MYSQL_USERNAME=root
      - JWT_SECRET_KEY=123456root
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - '/app/node_modules'
      
  
  mysql_server:
    image: mysql:8.1.0
    hostname: mysql
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    # volumes:
    #   - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mysql_server
      - MYSQL_PASSWORD=123456root
      - MYSQL_ROOT_PASSWORD=123456root
      - MYSQL_USER=user
      - MYSQL_USERNAME=root
      - JWT_SECRET_KEY=123456root
    healthcheck:
      test: ["CMD", "-u", "root" ,"ping","-p","12345root" ,"-h", "localhost"]
      timeout: 2s
      retries: 5