version: '3'
services:
  app:
    depends_on:
      - mysql_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - '/app/node_modules'
      
  
  mysql_server:
    image: mysql:8.1.0
    hostname: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mysql_server
      - MYSQL_PASSWORD=123456root
      - MYSQL_ROOT_PASSWORD=123456root
      - MYSQL_USERNAME=root
      - JWT_SECRET_KEY=123456root
    command: --bind-address=127.0.0.1
    expose:
      - "3307"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
